[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ika_account = "Dx7P74pmeMqgPG4iF3VpL5aZ6TZTMiPzcMULnpu2hyje"
mock_dwallet = "6sewJoZnLJN1hMzaYLySG61VSLiPoFzbA8Cyd7KJkwv"
test_cpi_owner = "C86ZbaTdqH5dHZ5sBRrNrpMUYJxjubk8Adt4fNT9RnLA"

[programs.devnet]
ika_account = "Dx7P74pmeMqgPG4iF3VpL5aZ6TZTMiPzcMULnpu2hyje"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
